Update st7735_buf.py
In pi pico , PWM.duty is not defined rather PWM.duty_u16
Thus if you use st7735 driver there will throw a error that
  AttributeError: type object 'PWM' has no attribute 'duty'
fixed duty(1023)  to  duty_u16(1023)