将PWM.duty替换成了PWM.duty_u16 (#2)
* Update st7735_buf.py

In pi pico , PWM.duty is not defined rather PWM.duty_u16
Thus if you use st7735 driver there will throw a error that
  AttributeError: type object 'PWM' has no attribute 'duty'
fixed duty(1023)  to  duty_u16(1023)

* Update st7735_spi.py

* Update st7789_buf.py

* Update st7789_spi.py